### ISSUE TITLE
Release the latest main branch

### ISSUE THREAD

**Issue by theNailz** [logzio/fluentd-docker-logs#7]
Could you release the latest `main` branch as Docker image on Docker Hub?

This branch contains a feature (additional fields; https://github.com/logzio/fluentd-docker-logs/pull/4), which is described on the Logz.io documentation, but the feature is not in the Docker image (!).

**Comment by ralongit** [comment]
Hello @theNailz ,

Thank you for bringing this to our attention, we have merged a fix in a new version. 
Please pull the latest image and try again.
